# Generated by Django 6.1 on 2026-08-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=30, verbose_name='Провайдер')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID в платёжной системе')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(default='rub', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'Обрабатывается'), ('succeeded', 'Оплачен'), ('failed', 'Ошибка'), ('canceled', 'Отменён'), ('refunded', 'Возвращён'), ('partially_refunded', 'Частично возвращён')], default='pending', max_length=20, verbose_name='Статус')),
                ('method', models.CharField(default='card', max_length=10, verbose_name='Способ')),
                ('redirect_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на оплату')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
