# Generated by Django 6.1 on 2026-08-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='kgs', max_length=3, verbose_name='Валюта'),
        ),
    ]
