# Generated by Django 6.1 on 2026-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Активна до')),
            ],
            options={
                'verbose_name': 'PIN-сессия аналитики',
                'verbose_name_plural': 'PIN-сессии аналитики',
            },
        ),
    ]
