# Generated by Django 6.1 on 2026-08-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма магазина')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка, %')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Комиссия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Комиссия',
                'verbose_name_plural': 'Комиссии',
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило комиссии',
                'verbose_name_plural': 'Правила комиссии',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('processing', 'Выполняется'), ('succeeded', 'Выплачено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('provider_payout_id', models.CharField(blank=True, max_length=255, verbose_name='ID в платёжной системе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доступно к выводу')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Заработано всего')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Кошелёк продавца',
                'verbose_name_plural': 'Кошельки продавцов',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Доход с заказа'), ('commission', 'Комиссия платформы'), ('payout', 'Выплата')], max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('-created_at',),
            },
        ),
    ]
