# Generated by Django 6.1 on 2026-08-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('orders', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rule', to='shops.shop', verbose_name='Магазин (пусто — глобально)'),
        ),
        migrations.AddField(
            model_name='payout',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.payout', verbose_name='Выплата'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.sellerwallet', verbose_name='Кошелёк'),
        ),
    ]
