# Generated by Django 6.1 on 2026-08-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('earn', 'Доход с заказа'), ('commission', 'Комиссия платформы'), ('payout', 'Выплата'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип'),
        ),
    ]
