# Generated by Django 6.1 on 2026-08-22 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initiator(apps, schema_editor):
    """Для старых диалогов по заказу инициатор — покупатель заказа."""
    Thread = apps.get_model("chat", "Thread")
    for thread in Thread.objects.filter(order__isnull=False, initiator__isnull=True):
        thread.initiator_id = thread.order.user_id
        thread.save(update_fields=["initiator"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_name_en_brand_name_ky_brand_name_ru_and_more'),
        ('chat', '0001_initial'),
        ('orders', '0002_initial'),
        ('shops', '0003_shop_description_en_shop_description_ky_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='chat/%Y/%m/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='thread',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_chat_threads', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор (покупатель)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='thread',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.RunPython(backfill_initiator, migrations.RunPython.noop),
    ]
