# Generated by Django 6.1 on 2026-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='support/%Y/%m/', verbose_name='Вложение'),
        ),
    ]
