# Generated by Django 6.1 on 2026-08-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_ky',
            field=models.CharField(max_length=120, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Название магазина'),
        ),
    ]
