# Generated by Django 6.1 on 2026-08-22 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='brand',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='approved', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
