# Generated by Django 6.1 on 2026-08-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('processing', 'В обработке'), ('preparing', 'Готовится'), ('shipped', 'Передан'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('paid', 'Оплачен')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('card', 'Картой онлайн'), ('cash', 'При получении'), ('sbp', 'СБП')], default='cash', max_length=10, verbose_name='Оплата')),
                ('recipient_name', models.CharField(max_length=120, verbose_name='Получатель')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('seller_comment', models.TextField(blank=True, verbose_name='Комментарий продавца')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название (снимок)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
    ]
